### ISSUE TITLE
Seeking new primary maintainer

### ISSUE THREAD

**Issue by davish** [obsidian-community/obsidian-full-calendar#528]
Hi all,

I'm sure it's clear by the time since the last release as well as the number of open issues that have gone un-responded to that, due to life being the chaotic and ever-changing thing that it is, I haven't had much time to work on or maintain Obsidian Full Calendar for a while now.

It's clear from the bug reports and feature requests that this is a popular plugin, and I do want to see it continue to be a part of Obsidian's vibrant plugin ecosystem.

To that end, I'm looking for a primary maintainer to take over from me. If you're interested, please send me an email -- you can find it in my GitHub profile or by clicking the little envelope on [my homepage](https://davi.sh/).

Thanks to all of you who have used and continue to use Obsidian Full Calendar, and I'm looking forward to see how this plugin grows going forward!

All the best,
-davish

**Comment by Dragonslayersakata** [comment]
Has there been any updates on this? I just found this plug-in and would really like it to continue.

**Comment by julesvirallinen** [comment]
Hi! I have initial interest in helping with development, commenting here as a reminder to myself. Primary maintainership is a lot of commitment though, so interested to see if we can find others interested. Are you looking to bow out completely, or still ready to maintain and read PRs?

**Comment by hyperupcall** [comment]
@davish Perhaps this repository can be moved over to [obsidian-community](https://github.com/obsidian-community)? There are several features that I've been wanting [to add](https://github.com/fox-brewery/obsidian-full-calendar), but I do not have the time to commit to being the sole primary maintainer. If the repository is moved to `obsidian-community`, then the load is shared. In that case, I'll be able to help by triaging issues and closing issues that are out of scope or closing duplicates and making the dev environment more reproducable (i encountered a few issues when forking and building this plugin for myself). That way, things are a lot more clear and easy for anybody else that wants to jump into things. I love this plugin and I wouldn't want to see it unmaintained.

cc @joethei @phibr0 @konhi @chrisgrieser

**Comment by chrisgrieser** [comment]
Yes, that can be done and is one of the reasons "obsidian community" exists.

**Comment by davish** [comment]
Hi @chrisgrieser and @hyperupcall,

Thanks for posting here! I think moving Full Calendar to obsidian-community sounds like a great way to ensure the sustainability of the plugin. What would the process look like to make this happen? Also happy to move this conversation to email -- you can find my address in my bio.

**Comment by joethei** [comment]
Hi @davish I've invited you to the obsidian-community org, once you have accepted it, go to the repository settings, scroll down and click the "Transfer ownership" button and select the org.

After after that is done I will update the entry in the community plugins list.

**Comment by linqian1400** [comment]
I'm interested in maintaining the project. @davish lmk how you want to take this. if it's transfered to the obsidian-community org I can contribute there as well.

**Comment by diorcula** [comment]
bump.
I am interested in updates regarding the continuation of this project

**Comment by davish** [comment]
Hi @chrisgrieser @joethei, apologies for the delay, but I just tried to accept the obsidian-community invite, and it unfortunately expired. Would it be possible for one of you to re-send the invite so I can transfer ownership? Thanks so much!

**Comment by joethei** [comment]
Hi @davish sorry for the delay, invited you again.

**Comment by davish** [comment]
The repository has been moved to @obsidian-community! I'll close this issue as completed.

**Comment by YouFoundJK** [comment]
Hey @davish @joethei,

Came across this today. I originally started my fork as a continuation of this amazing work (mainly to fix issues I ran into) a few months back, and it has since grown quite a bit in terms of usage — likely due to the lack of an actively maintained FOSS alternative.

My fork: https://github.com/YouFoundJK/plugin-full-calendar

Architecturally, it has significantly diverged (it has undergone at least two major rewrites), and the license is now GNU to accommodate FullCalendar’s premium features.

---

### Moving forward

Given the current level of divergence and independent development, I’m leaning towards treating this as a natural evolution of the project and making it a standalone repository (via GitHub fork detachment), while continuing to:

- properly credit and acknowledge the original project
- maintain it as a fully open-source project
- preserve compatibility where possible (though I can’t guarantee full backward compatibility at this point)

I did consider [pushing changes upstream](https://github.com/obsidian-community/obsidian-full-calendar/pull/596), but given the scale of architectural differences and potential breaking changes, this likely wouldn’t be practical or beneficial as was rightly pointed out in that PR. To this extent I have also started a request to add it into the [community plugin](https://github.com/YouFoundJK/plugin-full-calendar/issues/206).

---

### Rough vision going forward

- I’m exploring a privacy-first reminder system (especially for Linux/Windows workflows), likely as a daemon syncing with the internal `EventCache`
- Expanding more on the analysis side → https://youfoundjk.github.io/plugin-full-calendar/user/chrono_analyser/

---

Would love to hear your thoughts — and thanks again for the original project, it’s been a fantastic foundation to build on 🙌
